### ISSUE TITLE
v4.0.0-S10 - Crate protect issue

### ISSUE THREAD

**Issue by CaptDarkStar** [ConnorLinfoot/CratesPlus#125]
Seems that crates are only protected when first placed down. After you reload the config, or restart the server, it loses the protection on the crate. To be more specific, when I left click in creative, the crate is accidentally destroyed instead of requiring me to crouch click to destroy/remove. Only gives the "Sneak to break crate" message on newly placed crates until any reload/reset occurs.

**Comment by Sikatsu** [comment]
So that's why my crates randomly disappeared? I was already thinking I had a ghost in my server or something.

**Comment by ConnorLinfoot** [comment]
Yeah seems this is caused because block metadata (Which CratesPlus uses now) isn't kept after restart, will fix it in the next snapshot.

**Comment by ConnorLinfoot** [comment]
This should now be fixed in snapshot 11 (You will need to replace the crates)

**Comment by CaptDarkStar** [comment]
This issue doesnt seem to be fixed in snapshot 11. The is actually an issue with it loading. This issue can be seen here: http://pastebin.com/nh7D5f1L

**Comment by ConnorLinfoot** [comment]
Can you post your config.yml and data.yml (That should now exist)?

**Comment by CaptDarkStar** [comment]
Here is my config.yml: http://pastebin.com/jDVW1KhP
Here is my data.yml: http://pastebin.com/qcfxsH2q

**Comment by ConnorLinfoot** [comment]
Ahh, for some reason the data.yml has put in extra dashes. Will get it fixed in the next couple of hours.

**Comment by CaptDarkStar** [comment]
Sounds good. I noticed that after I posted the data file. I didn't even know it was a newly generated file till you asked for it. I hope I have been more helpful then annoying with this plugin :P

**Comment by ConnorLinfoot** [comment]
No you're not annoying me, it's helpful of course to find these bugs so they don't just get missed!

I've pushed snapshot 12 which *should* fix it, you'll need to place the crate again cause I changed the data.yml layout. Let me know if it's woring :smile:

**Comment by CaptDarkStar** [comment]
I am glad you dont find it annoying. You would be surprised how many developers find it annoying, especially when they have two versions going on. 

As for snapshot 12, I am still getting the same error and the same protection issue. The new data structure seems to still be doing extra dash lines: https://gyazo.com/3be6a8893ab70f7fe26b58c4ab4954b0

**Comment by ConnorLinfoot** [comment]
Really not sure why this is happening, are you able to test without other plugins? Tested this a few times and can't get the same issue you're having :/

**Comment by ConnorLinfoot** [comment]
Oh crap, I know what this is! It's negative cords :') I'll fix this! xD

**Comment by ConnorLinfoot** [comment]
Try snapshot 13 now xD I'd imagine it should work fine. Now uses pipes "|" to split instead of dashes.

**Comment by CaptDarkStar** [comment]
Still doesn't seem to be working currently both with my plugins as well as without other plugins. I also tried this out in 1.8 and 1.9 versions and it throws two different errors for the version. Here are some pastebins:

1.8 Error: http://pastebin.com/2yZ0hhdc
1.9 Error: http://pastebin.com/CT0xF4TK

**Comment by ConnorLinfoot** [comment]
Not having a good day with this (Still at work and trying to quickly push without testing xD) Try the snapshot 14, if it still doesn't work I'll check later when I'm home and actually *test* it XD

**Comment by CaptDarkStar** [comment]
Well... I am not sure how to tell you this... But... IT WORKED! :)
There doesn't seem to be any issues in either 1.8 or 1.9 game versions.

**Comment by ConnorLinfoot** [comment]
Awesome! :smiley: Thanks for your help with testing this!

**Comment by CaptDarkStar** [comment]
Not a problem at all. Always happy to do any additional testing whenever needed. This has been such a great addition to my server and very happy to help where possible :)
